const preguntas = {
  cafe: [
    // Historia - 200 preguntas
  { p: "¿Quién fue el primer presidente de Estados Unidos?", r: "George Washington" },
  { p: "¿En qué año comenzó la Segunda Guerra Mundial?", r: "1939" },
  { p: "¿Qué civilización construyó las pirámides?", r: "Los egipcios" },
  { p: "¿Quién descubrió América?", r: "Cristóbal Colón" },
  { p: "¿En qué año cayó el Muro de Berlín?", r: "1989" },
  { p: "¿Qué imperio dominó gran parte de Sudamérica antes de la llegada de los españoles?", r: "El Imperio Inca" },
  { p: "¿Cuál fue la causa principal de la Revolución Francesa?", r: "La desigualdad social y económica" },
  { p: "¿Quién fue Napoleón Bonaparte?", r: "Un líder militar y emperador francés" },
  { p: "¿Cuál fue el resultado de la Guerra Civil de Estados Unidos?", r: "La abolición de la esclavitud" },
  { p: "¿Qué tratado puso fin a la Primera Guerra Mundial?", r: "El Tratado de Versalles" },
  { p: "¿Quién fue la Reina de Inglaterra durante la época isabelina?", r: "Isabel I" },
  { p: "¿Qué civilización antigua se ubicaba en Mesopotamia?", r: "Los sumerios" },
  { p: "¿Qué evento marcó el inicio de la Edad Media?", r: "La caída del Imperio Romano de Occidente" },
  { p: "¿Quién fue Simón Bolívar?", r: "Un líder de la independencia de varios países sudamericanos" },
  { p: "¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", r: "1776" },
  { p: "¿Qué fue la Guerra Fría?", r: "Un conflicto ideológico entre EE.UU. y la URSS" },
  { p: "¿Qué evento detonó la Primera Guerra Mundial?", r: "El asesinato del archiduque Francisco Fernando" },
  { p: "¿Quién fue Mahatma Gandhi?", r: "Líder del movimiento de independencia de India" },
  { p: "¿Qué imperio dominó gran parte de Europa durante la Edad Media?", r: "El Imperio Romano Germánico" },
  { p: "¿Qué civilización construyó Machu Picchu?", r: "Los incas" },
  { p: "¿Qué era la ruta de la seda?", r: "Una red de rutas comerciales entre Asia y Europa" },
  { p: "¿Cuál fue la capital del Imperio Azteca?", r: "Tenochtitlán" },
  { p: "¿Qué país fue conocido como la URSS?", r: "La Unión Soviética" },
  { p: "¿En qué año terminó la Primera Guerra Mundial?", r: "1918" },
{ p: "¿Qué rey francés fue conocido como el Rey Sol?", r: "Luis XIV" },
{ p: "¿Qué imperio construyó la Gran Muralla China?", r: "El Imperio Chino bajo la dinastía Qin" },
{ p: "¿En qué siglo ocurrió la caída del Imperio Romano de Occidente?", r: "En el siglo V" },
{ p: "¿Qué tratado puso fin a la Guerra de los Treinta Años?", r: "La Paz de Westfalia" },
{ p: "¿Quién fue el conquistador del Imperio Azteca?", r: "Hernán Cortés" },
{ p: "¿Qué conflicto enfrentó a Inglaterra y las Trece Colonias?", r: "La Guerra de Independencia de Estados Unidos" },
{ p: "¿Qué fue el feudalismo?", r: "Un sistema político y económico de la Edad Media basado en la posesión de tierras" },
{ p: "¿En qué siglo comenzó la Edad Moderna?", r: "En el siglo XV" },
{ p: "¿Qué emperador dividió el Imperio Romano en dos?", r: "Diocleciano" },
{ p: "¿Qué reina inglesa fue hija de Enrique VIII y Ana Bolena?", r: "Isabel I" },
{ p: "¿Qué batalla detuvo la expansión musulmana en Europa en el año 732?", r: "La Batalla de Poitiers" },
{ p: "¿Qué guerra enfrentó a Inglaterra y Francia por el trono francés?", r: "La Guerra de los Cien Años" },
{ p: "¿Qué civilización precolombina tuvo su capital en Cuzco?", r: "La civilización inca" },
{ p: "¿Qué líder macedonio conquistó gran parte de Asia?", r: "Alejandro Magno" },
{ p: "¿Qué evento provocó la entrada de EE.UU. en la Segunda Guerra Mundial?", r: "El ataque a Pearl Harbor" },
{ p: "¿Qué imperio tenía su capital en Tenochtitlán?", r: "El Imperio Azteca" },
{ p: "¿Quién fue el principal líder revolucionario de México?", r: "Emiliano Zapata" },
{ p: "¿En qué año comenzó la Primera Guerra Mundial?", r: "1914" },
{ p: "¿Qué imperio se caracterizó por su uso del alfabeto cuneiforme?", r: "El Imperio Sumerio" },
{ p: "¿Qué faraón egipcio intentó imponer el monoteísmo?", r: "Akenatón" },
{ p: "¿Qué país fue gobernado por Mao Zedong?", r: "China" },
{ p: "¿Quién fue el primer presidente de Colombia?", r: "Simón Bolívar" },
{ p: "¿Qué imperio tenía su centro en lo que hoy es Estambul?", r: "El Imperio Bizantino" },
{ p: "¿Qué conflicto bélico duró de 1939 a 1945?", r: "La Segunda Guerra Mundial" },
{ p: "¿Qué civilización es famosa por su sistema de escritura jeroglífica?", r: "La civilización egipcia" },
{ p: "¿Quién fue el caudillo español durante la Guerra Civil Española?", r: "Francisco Franco" },
{ p: "¿Qué conflicto enfrentó a EE.UU. y la URSS sin combate directo?", r: "La Guerra Fría" },
{ p: "¿Qué fue el Plan Marshall?", r: "Un programa estadounidense para reconstruir Europa tras la Segunda Guerra Mundial" },
{ p: "¿Qué rey firmó la independencia de Brasil?", r: "Pedro I de Brasil" },
{ p: "¿Qué ciudad fue dividida por un muro durante la Guerra Fría?", r: "Berlín" },
{ p: "¿Quién fue el principal libertador de Argentina, Chile y Perú?", r: "José de San Martín" },
{ p: "¿Qué imperio controlaba Egipto antes de la llegada de Alejandro Magno?", r: "El Imperio Persa" },
{ p: "¿Qué batalla famosa ocurrió en 1815?", r: "La Batalla de Waterloo" },
{ p: "¿Qué monarca español era conocido como 'el Rey Prudente'?", r: "Felipe II" },
{ p: "¿Qué imperio surgió tras la caída del Imperio Bizantino?", r: "El Imperio Otomano" },
{ p: "¿Quién fue la primera mujer en gobernar un país en América Latina?", r: "Isabel Perón" },
{ p: "¿Qué cultura prehispánica floreció en la península de Yucatán?", r: "La cultura maya" },
{ p: "¿Qué periodo se caracterizó por el uso intensivo de la máquina de vapor?", r: "La Revolución Industrial" },
{ p: "¿Qué imperio fue derrotado por los griegos en las Guerras Médicas?", r: "El Imperio Persa" },
{ p: "¿Qué hecho marcó el inicio del cristianismo?", r: "La muerte y resurrección de Jesús" },
{ p: "¿Qué papa inició las Cruzadas?", r: "Urbano II" },
{ p: "¿Qué tratado terminó la Guerra de Independencia de EE.UU.?", r: "El Tratado de París (1783)" },
{ p: "¿Quién fue el líder de la independencia haitiana?", r: "Toussaint Louverture" },
{ p: "¿Qué revolución estableció la República Popular China?", r: "La Revolución China de 1949" },
{ p: "¿Qué país fue gobernado por Atatürk?", r: "Turquía" },
{ p: "¿Qué evento marcó el final de la Segunda Guerra Mundial?", r: "La rendición de Japón" },
{ p: "¿Qué civilización desarrolló una escritura con nudos llamada quipu?", r: "Los incas" },
{ p: "¿Qué rey inglés rompió con la Iglesia Católica?", r: "Enrique VIII" },
{ p: "¿Qué imperio fue liderado por Gengis Kan?", r: "El Imperio Mongol" }
{ p: "¿Qué guerra se libró entre el norte y el sur de EE.UU.?", r: "La Guerra Civil" },
{ p: "¿Quién fue el dictador italiano durante la Segunda Guerra Mundial?", r: "Benito Mussolini" },
{ p: "¿Qué imperio construyó el Coliseo?", r: "El Imperio Romano" },
{ p: "¿Quién fue el primer emperador romano?", r: "Augusto" },
{ p: "¿Qué civilización usaba jeroglíficos?", r: "La egipcia" },
{ p: "¿Qué líder sudafricano luchó contra el apartheid?", r: "Nelson Mandela" },
{ p: "¿Qué país lanzó las bombas atómicas en Hiroshima y Nagasaki?", r: "Estados Unidos" },
{ p: "¿Qué tratado puso fin a la Primera Guerra Mundial?", r: "El Tratado de Versalles" },
{ p: "¿Quién fue el zar durante la Revolución Rusa?", r: "Nicolás II" },
{ p: "¿Qué país fue invadido por Alemania para iniciar la Segunda Guerra Mundial?", r: "Polonia" },
{ p: "¿En qué año comenzó la Revolución Francesa?", r: "1789" },
{ p: "¿Qué imperio estaba gobernado por los zares?", r: "El Imperio Ruso" },
{ p: "¿Qué evento ocurrió el 11 de septiembre de 2001?", r: "Los atentados a las Torres Gemelas" },
{ p: "¿Cuál fue la última dinastía china?", r: "La dinastía Qing" },
{ p: "¿Quién era el líder de los nazis?", r: "Adolf Hitler" },
{ p: "¿Qué guerra enfrentó a EE.UU. con Vietnam?", r: "La Guerra de Vietnam" },
{ p: "¿Quién descubrió la ruta marítima a la India?", r: "Vasco da Gama" },
{ p: "¿Quién fue Juana de Arco?", r: "Una heroína francesa y santa" },
{ p: "¿Qué país colonizó gran parte de América del Sur?", r: "España" },
{ p: "¿Quién fue Simón Bolívar?", r: "El Libertador de América del Sur" },
{ p: "¿Qué civilización creó el calendario maya?", r: "La civilización maya" },
{ p: "¿Quién escribió la Constitución de EE.UU.?", r: "Varios padres fundadores" },
{ p: "¿Qué imperio cayó en 1453?", r: "El Imperio Bizantino" },
{ p: "¿Qué rey francés fue guillotinado durante la Revolución?", r: "Luis XVI" },
{ p: "¿Qué conflicto se llamó la Gran Guerra?", r: "La Primera Guerra Mundial" },
{ p: "¿Qué país fue gobernado por Stalin?", r: "La Unión Soviética" },

  ],

  verde: [
    // Ciencia - 200 preguntas
{ p: "¿Cuál es el órgano encargado de bombear sangre en el cuerpo humano?", r: "El corazón" },
{ p: "¿Qué planeta es conocido como el planeta rojo?", r: "Marte" },
{ p: "¿Qué gas es esencial para la respiración humana?", r: "Oxígeno" },
{ p: "¿Qué científico formuló la teoría de la relatividad?", r: "Albert Einstein" },
{ p: "¿Cómo se llama el proceso por el cual las plantas fabrican su alimento?", r: "Fotosíntesis" },
{ p: "¿Cuál es el hueso más largo del cuerpo humano?", r: "El fémur" },
{ p: "¿Qué partícula tiene carga negativa?", r: "Electrón" },
{ p: "¿Qué tipo de energía proviene del sol?", r: "Energía solar" },
{ p: "¿Qué mamífero pone huevos?", r: "Ornitorrinco" },
{ p: "¿Qué órgano es responsable de filtrar la sangre?", r: "Riñón" },
{ p: "¿Qué gas utilizan las plantas en la fotosíntesis?", r: "Dióxido de carbono" },
{ p: "¿Qué planeta es famoso por su color azul?", r: "Neptuno" },
{ p: "¿Qué parte del cuerpo humano contiene el cráneo?", r: "La cabeza" },
{ p: "¿Qué instrumento mide la presión atmosférica?", r: "Barómetro" },
{ p: "¿Qué científico desarrolló las leyes del movimiento?", r: "Isaac Newton" },
{ p: "¿Cuál es el órgano más grande del cuerpo humano?", r: "La piel" },
{ p: "¿Qué célula transporta oxígeno en la sangre?", r: "Glóbulo rojo" },
{ p: "¿Qué animal tiene la lengua más larga en proporción a su cuerpo?", r: "El camaleón" },
{ p: "¿Qué es un átomo?", r: "La unidad básica de la materia" },
{ p: "¿Cómo se llama el cambio de líquido a gas?", r: "Evaporación" },
{ p: "¿Qué animal tiene el corazón más grande?", r: "La ballena azul" },
{ p: "¿Qué es una neurona?", r: "Una célula del sistema nervioso" },
{ p: "¿Qué planeta tiene el mayor número de lunas?", r: "Saturno" },
{ p: "¿Qué capa de la atmósfera protege de los rayos UV?", r: "La capa de ozono" },
{ p: "¿Qué elemento tiene el símbolo H?", r: "Hidrógeno" },
{ p: "¿Qué tipo de energía utiliza un panel solar?", r: "Energía luminosa" },
{ p: "¿Qué animal es capaz de volar hacia atrás?", r: "El colibrí" },
{ p: "¿Qué hueso protege el cerebro?", r: "El cráneo" },
{ p: "¿Qué órgano humano detecta los sonidos?", r: "El oído" },
{ p: "¿Qué planeta es famoso por su gran mancha roja?", r: "Júpiter" },
{ p: "¿Qué parte de la célula contiene el ADN?", r: "El núcleo" },
{ p: "¿Qué elemento químico tiene el símbolo O?", r: "Oxígeno" },
{ p: "¿Qué estado de la materia no tiene forma ni volumen fijos?", r: "Gas" },
{ p: "¿Qué científico desarrolló la tabla periódica?", r: "Dmitri Mendeléyev" },
{ p: "¿Qué fuerza mantiene a los planetas girando alrededor del Sol?", r: "La gravedad" },
{ p: "¿Qué animal es conocido por cambiar de color?", r: "El camaleón" },
{ p: "¿Qué se necesita para que haya combustión?", r: "Oxígeno" },
{ p: "¿Qué parte del cuerpo controla los pensamientos?", r: "El cerebro" },
{ p: "¿Qué es un ecosistema?", r: "Una comunidad de seres vivos y su entorno" },
{ p: "¿Qué órgano permite saborear los alimentos?", r: "La lengua" },
{ p: "¿Qué es la mitosis?", r: "La división celular en células hijas idénticas" },
{ p: "¿Qué planeta tiene más volcanes?", r: "Venus" },
{ p: "¿Qué célula es responsable de defender el cuerpo?", r: "Glóbulo blanco" },
{ p: "¿Qué es un fósil?", r: "Resto de un ser vivo del pasado" },
{ p: "¿Qué líquido ayuda a digerir los alimentos en el estómago?", r: "Ácido gástrico" },
{ p: "¿Qué aparato convierte la energía mecánica en eléctrica?", r: "Generador" },
{ p: "¿Qué se mide en litros?", r: "El volumen" },
{ p: "¿Qué material se usa para hacer imanes?", r: "Hierro" },
{ p: "¿Qué animal tiene el cerebro más grande en proporción a su cuerpo?", r: "El delfín" },
{ p: "¿Qué parte de la célula produce energía?", r: "Mitocondria" },
{ p: "¿Qué especie es considerada el antepasado del ser humano?", r: "Australopithecus" },
{ p: "¿Qué tipo de energía usan los molinos de viento?", r: "Energía eólica" },
{ p: "¿Qué ocurre cuando dos placas tectónicas se mueven?", r: "Un terremoto" },
{ p: "¿Qué planeta tiene estaciones similares a las de la Tierra?", r: "Marte" },
{ p: "¿Qué mineral es esencial para los huesos?", r: "Calcio" },
{ p: "¿Qué son los glóbulos rojos?", r: "Células que transportan oxígeno" },
{ p: "¿Qué animal tiene la mayor esperanza de vida?", r: "La tortuga de las Galápagos" },
{ p: "¿Qué provoca las mareas?", r: "La gravedad de la Luna" },
{ p: "¿Qué nombre recibe el cambio de gas a líquido?", r: "Condensación" }
{ p: "¿Qué planeta tiene un sistema de anillos?", r: "Saturno" },
{ p: "¿Cómo se llama la fuerza que nos mantiene en el suelo?", r: "Gravedad" },
{ p: "¿Qué metal se encuentra en el centro de la Tierra?", r: "Hierro" },
{ p: "¿Qué parte del ojo regula la entrada de luz?", r: "La pupila" },
{ p: "¿Qué instrumento se usa para medir la temperatura?", r: "Termómetro" },
{ p: "¿Qué animales son conocidos por su metamorfosis completa?", r: "Las mariposas" },
{ p: "¿Qué enfermedad afectó al mundo en 2020?", r: "COVID-19" },
{ p: "¿Qué órgano produce insulina?", r: "El páncreas" },
{ p: "¿Cuál es el planeta más cercano al Sol?", r: "Mercurio" },
{ p: "¿Qué sistema corporal controla los movimientos voluntarios?", r: "Sistema nervioso" },
{ p: "¿Qué gas es el más abundante en la atmósfera?", r: "Nitrógeno" },
{ p: "¿Qué parte de la planta absorbe nutrientes del suelo?", r: "Las raíces" },
{ p: "¿Qué animales pertenecen al grupo de los anfibios?", r: "Ranas, sapos y salamandras" },
{ p: "¿Qué órgano permite respirar a los humanos?", r: "Pulmones" },
{ p: "¿Qué tipo de célula no tiene núcleo definido?", r: "Procariota" },
{ p: "¿Qué tipo de sangre es el donante universal?", r: "O negativo" },
{ p: "¿Qué astro da luz y calor a la Tierra?", r: "El Sol" },
{ p: "¿Cómo se llama la ciencia que estudia los seres vivos?", r: "Biología" },
{ p: "¿Qué vitamina se obtiene del sol?", r: "Vitamina D" },
{ p: "¿Qué animal puede regenerar sus extremidades?", r: "La estrella de mar" },
{ p: "¿Qué fenómeno meteorológico produce rayos y truenos?", r: "Tormenta eléctrica" },
{ p: "¿Qué planeta es el más grande del sistema solar?", r: "Júpiter" },
{ p: "¿Qué unidad se usa para medir la intensidad eléctrica?", r: "Amperio" },
{ p: "¿Qué nombre recibe el ADN en las células?", r: "Material genético" },
{ p: "¿Qué órgano conecta la boca con el estómago?", r: "Esófago" },
{ p: "¿Cómo se llama el estudio de los fósiles?", r: "Paleontología" },
{ p: "¿Qué parte del cuerpo produce glóbulos rojos?", r: "Médula ósea" },
{ p: "¿Qué órgano es responsable de la digestión química?", r: "El estómago" },
{ p: "¿Qué nombre recibe el agua en estado gaseoso?", r: "Vapor" },
{ p: "¿Qué fenómeno hace que los objetos floten en el agua?", r: "Empuje o flotación" },
{ p: "¿Cuál es el único satélite natural de la Tierra?", r: "La Luna" },
{ p: "¿Qué aparato se usa para ver objetos muy pequeños?", r: "Microscopio" },
{ p: "¿Qué animal es el más rápido del mundo?", r: "El halcón peregrino" },
{ p: "¿Qué proceso permite que el hielo se convierta en agua?", r: "Fusión" },
{ p: "¿Qué líquido del cuerpo transporta oxígeno?", r: "La sangre" },
{ p: "¿Qué es un eclipse?", r: "La ocultación de un cuerpo celeste por otro" },
{ p: "¿Qué parte del cerebro controla el equilibrio?", r: "El cerebelo" },
{ p: "¿Qué planeta tiene un día más largo que su año?", r: "Venus" },
{ p: "¿Qué ciencia estudia los planetas y estrellas?", r: "Astronomía" },
{ p: "¿Qué órgano produce bilis?", r: "El hígado" }
  ],

  beige: [
    // Arte y Literatura - 200 preguntas
{ p: "¿Qué es un soneto?", r: "Un poema de 14 versos" },
{ p: "¿Quién escribió *El amor en los tiempos del cólera*?", r: "Gabriel García Márquez" },
{ p: "¿Quién es el autor de *Pedro Páramo*?", r: "Juan Rulfo" },
{ p: "¿Qué famoso pintor usó el método del puntillismo?", r: "Georges Seurat" },
{ p: "¿Qué dramaturgo español escribió *La vida es sueño*?", r: "Calderón de la Barca" },
{ p: "¿Qué poeta escribió *Alturas de Macchu Picchu*?", r: "Pablo Neruda" },
{ p: "¿Qué escritora mexicana ganó el Premio Cervantes en 2013?", r: "Elena Poniatowska" },
{ p: "¿Qué novela de Mary Shelley es considerada la primera de ciencia ficción?", r: "*Frankenstein*" },
{ p: "¿Qué escultor renacentista creó *El David*?", r: "Miguel Ángel" },
{ p: "¿Qué poeta escribió *Campos de Castilla*?", r: "Antonio Machado" },
{ p: "¿Quién pintó *El Guernica*?", r: "Pablo Picasso" },
{ p: "¿Qué obra literaria trata del capitán Ahab y una ballena?", r: "*Moby Dick*" },
{ p: "¿Qué autor escribió *La Metamorfosis*?", r: "Franz Kafka" },
{ p: "¿Qué escritor ruso es autor de *Ana Karenina*?", r: "León Tolstói" },
{ p: "¿Qué corriente artística prioriza la expresión emocional?", r: "Expresionismo" },
{ p: "¿Qué pintor español es famoso por sus pinturas negras?", r: "Francisco de Goya" },
{ p: "¿Quién escribió *Los miserables*?", r: "Victor Hugo" },
{ p: "¿Qué poeta escribió *Rimas y leyendas*?", r: "Gustavo Adolfo Bécquer" },
{ p: "¿Qué escritor escribió *El túnel*?", r: "Ernesto Sabato" },
{ p: "¿Qué autor creó a Sherlock Holmes?", r: "Arthur Conan Doyle" },
{ p: "¿Qué poeta escribió *Oda a la alegría*?", r: "Friedrich Schiller" },
{ p: "¿Qué autora escribió *Orgullo y prejuicio*?", r: "Jane Austen" },
{ p: "¿Qué corriente artística pintó Monet?", r: "Impresionismo" },
{ p: "¿Qué autor escribió *Fahrenheit 451*?", r: "Ray Bradbury" },
{ p: "¿Qué escritor colombiano escribió *El coronel no tiene quien le escriba*?", r: "Gabriel García Márquez" },
{ p: "¿Qué libro tiene como personaje principal a Gregorio Samsa?", r: "*La Metamorfosis*" },
{ p: "¿Qué pintor mexicano es conocido por su estilo muralista?", r: "Diego Rivera" }
{ p: "¿Quién escribió *Cien años de soledad*?", r: "Gabriel García Márquez" },
{ p: "¿Qué pintor es conocido por cortarse una oreja?", r: "Vincent van Gogh" },
{ p: "¿Quién escribió *Don Quijote de la Mancha*?", r: "Miguel de Cervantes" },
{ p: "¿Qué escritor británico creó al personaje de Harry Potter?", r: "J.K. Rowling" },
{ p: "¿En qué país nació Pablo Picasso?", r: "España" },
{ p: "¿Cuál es la obra más famosa de Leonardo da Vinci?", r: "La Mona Lisa" },
{ p: "¿Qué autor escribió *Romeo y Julieta*?", r: "William Shakespeare" },
{ p: "¿Qué poeta chileno ganó el Nobel en 1971?", r: "Pablo Neruda" },
{ p: "¿Quién pintó el techo de la Capilla Sixtina?", r: "Miguel Ángel" },
{ p: "¿Cuál es el verdadero nombre de Mark Twain?", r: "Samuel Langhorne Clemens" },
{ p: "¿Qué novela comienza con 'En un lugar de la Mancha'?", r: "*Don Quijote de la Mancha*" },
{ p: "¿Qué es un haiku?", r: "Un poema japonés corto" },
{ p: "¿Quién escribió *La Divina Comedia*?", r: "Dante Alighieri" },
{ p: "¿Qué movimiento artístico fundó Salvador Dalí?", r: "Surrealismo" },
{ p: "¿Qué autor escribió *Crimen y castigo*?", r: "Fiódor Dostoyevski" },
{ p: "¿Qué pintor español es famoso por sus obras cubistas?", r: "Pablo Picasso" },
{ p: "¿Quién escribió *El principito*?", r: "Antoine de Saint-Exupéry" },
{ p: "¿Qué escritor argentino es autor de *Ficciones*?", r: "Jorge Luis Borges" },
{ p: "¿Qué autor escribió *1984* y *Rebelión en la granja*?", r: "George Orwell" },
{ p: "¿Qué artista pintó *La noche estrellada*?", r: "Vincent van Gogh" },
{ p: "¿Quién escribió *Rayuela*?", r: "Julio Cortázar" },
{ p: "¿Qué obra escribió Homero además de *La Ilíada*?", r: "*La Odisea*" },
{ p: "¿Qué escritor noruego escribió *Casa de muñecas*?", r: "Henrik Ibsen" },
{ p: "¿Qué escritor escribió *Cuentos de la selva*?", r: "Horacio Quiroga" },
{ p: "¿Quién es el autor de *Los detectives salvajes*?", r: "Roberto Bolaño" },
{ p: "¿Qué escritor colombiano ganó el Nobel de Literatura en 1982?", r: "Gabriel García Márquez" },
{ p: "¿Quién escribió *La casa de los espíritus*?", r: "Isabel Allende" },
{ p: "¿Qué artista es conocido por pintar relojes derretidos?", r: "Salvador Dalí" },
{ p: "¿Qué autor escribió *Ensayo sobre la ceguera*?", r: "José Saramago" },
{ p: "¿Qué novela tiene como personaje principal a Emma Bovary?", r: "*Madame Bovary*" },
{ p: "¿Qué poeta escribió *El cuervo*?", r: "Edgar Allan Poe" },
{ p: "¿Qué dramaturgo escribió *Hamlet*?", r: "William Shakespeare" },
{ p: "¿Quién es el autor de *La insoportable levedad del ser*?", r: "Milan Kundera" },
{ p: "¿Qué escritor escribió *Don Juan Tenorio*?", r: "José Zorrilla" },
{ p: "¿Qué autor escribió *La náusea*?", r: "Jean-Paul Sartre" },
{ p: "¿Quién escribió *La señora Dalloway*?", r: "Virginia Woolf" },
{ p: "¿Qué pintor es conocido por sus girasoles?", r: "Vincent van Gogh" },
{ p: "¿Qué autor escribió *Demian*?", r: "Hermann Hesse" },
{ p: "¿Qué escritora inglesa escribió *Cumbres Borrascosas*?", r: "Emily Brontë" },
{ p: "¿Qué artista pintó *El nacimiento de Venus*?", r: "Sandro Botticelli" },
{ p: "¿Quién escribió *La tregua*?", r: "Mario Benedetti" },
{ p: "¿Qué autor escribió *Drácula*?", r: "Bram Stoker" },
{ p: "¿Qué autor escribió *La guerra del fin del mundo*?", r: "Mario Vargas Llosa" },
{ p: "¿Qué pintor pintó *El jardín de las delicias*?", r: "El Bosco" },
{ p: "¿Qué novelista escribió *El extranjero*?", r: "Albert Camus" },
{ p: "¿Qué poeta escribió *Poema 20*?", r: "Pablo Neruda" },
{ p: "¿Qué autor escribió *La colmena*?", r: "Camilo José Cela" },
{ p: "¿Qué movimiento artístico representó Jackson Pollock?", r: "Expresionismo abstracto" },
{ p: "¿Qué escritor escribió *Las venas abiertas de América Latina*?", r: "Eduardo Galeano" },
{ p: "¿Qué escritor es conocido por *El Aleph*?", r: "Jorge Luis Borges" },
{ p: "¿Quién pintó *La última cena*?", r: "Leonardo da Vinci" },
{ p: "¿Qué autor es famoso por la novela *It*?", r: "Stephen King" },
{ p: "¿Qué pintora mexicana es conocida por sus autorretratos?", r: "Frida Kahlo" },
{ p: "¿Qué poeta escribió *Soledades*?", r: "Antonio Machado" },
{ p: "¿Qué autor escribió *Viaje al centro de la Tierra*?", r: "Julio Verne" },
{ p: "¿Qué escritor fue creador de *Alicia en el país de las maravillas*?", r: "Lewis Carroll" },
{ p: "¿Qué autor escribió *La vuelta al mundo en 80 días*?", r: "Julio Verne" },
{ p: "¿Qué movimiento artístico se caracteriza por el uso de colores puros y formas simplificadas?", r: "Fauvismo" },
{ p: "¿Qué escritora francesa escribió *El segundo sexo*?", r: "Simone de Beauvoir" },
{ p: "¿Qué poeta escribió *Romancero gitano*?", r: "Federico García Lorca" },
{ p: "¿Qué autor escribió *Crónica de una muerte anunciada*?", r: "Gabriel García Márquez" },
{ p: "¿Qué dramaturgo escribió *Bodas de sangre*?", r: "Federico García Lorca" },
{ p: "¿Qué pintor es famoso por su estilo cubista junto a Georges Braque?", r: "Pablo Picasso" },
{ p: "¿Qué autor escribió *Los juegos del hambre*?", r: "Suzanne Collins" },
{ p: "¿Qué artista esculpió *El Pensador*?", r: "Auguste Rodin" },
{ p: "¿Qué pintor español desarrolló el estilo conocido como 'pinturas negras'?", r: "Francisco de Goya" },
{ p: "¿Qué autor creó el personaje de Tom Sawyer?", r: "Mark Twain" },
{ p: "¿Qué autor escribió *Las aventuras de Huckleberry Finn*?", r: "Mark Twain" },
{ p: "¿Qué autor escribió *La montaña mágica*?", r: "Thomas Mann" },
{ p: "¿Qué autor escribió *La madre*?", r: "Máximo Gorki" },
{ p: "¿Qué pintor es conocido por sus autorretratos con relojes rotos?", r: "Salvador Dalí" },
{ p: "¿Qué autora escribió *La campana de cristal*?", r: "Sylvia Plath" },
{ p: "¿Qué autor escribió *Los pilares de la Tierra*?", r: "Ken Follett" }

  ],

  azul: [
    // Deportes - 200 preguntas
{ p: "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?", r: "1896" },
{ p: "¿Cuál es el país con más Copas del Mundo de fútbol ganadas?", r: "Brasil" },
{ p: "¿Qué tenista ha ganado más títulos de Grand Slam?", r: "Novak Djokovic" },
{ p: "¿Qué futbolista es conocido como 'La Pulga'?", r: "Lionel Messi" },
{ p: "¿En qué deporte se usa una tabla y una vela?", r: "Windsurf" },
{ p: "¿Qué selección ganó el Mundial de Fútbol en 2018?", r: "Francia" },
{ p: "¿Qué país ha ganado más medallas olímpicas en total?", r: "Estados Unidos" },
{ p: "¿Cuál es el deporte principal en India?", r: "Críquet" },
{ p: "¿Quién es el máximo goleador histórico de la Champions League?", r: "Cristiano Ronaldo" },
{ p: "¿En qué país se celebraron los Juegos Olímpicos de 2020?", r: "Japón" },
{ p: "¿Cuántos jugadores hay en un equipo de voleibol en cancha?", r: "6" },
{ p: "¿Qué ciclista ganó 7 Tours de Francia consecutivos?", r: "Lance Armstrong (títulos luego retirados)" },
{ p: "¿Cuál es el equipo con más títulos en la NBA?", r: "Boston Celtics" },
{ p: "¿Qué deportista es apodado 'Bolt'?", r: "Usain Bolt" },
{ p: "¿Qué boxeador fue conocido como 'The Greatest'?", r: "Muhammad Ali" },
{ p: "¿En qué deporte se destacan los All Blacks?", r: "Rugby" },
{ p: "¿Cuántos sets se juegan en un partido de tenis masculino de Grand Slam?", r: "5" },
{ p: "¿Cuál es el país con más títulos en la Copa Davis?", r: "Estados Unidos" },
{ p: "¿Qué piloto de Fórmula 1 tiene más campeonatos mundiales?", r: "Lewis Hamilton (empatado con Schumacher)" },
{ p: "¿Quién fue el primer campeón mundial de ajedrez?", r: "Wilhelm Steinitz" },
{ p: "¿Qué futbolista argentino ganó el Balón de Oro en 2023?", r: "Lionel Messi" },
{ p: "¿En qué país se originó el judo?", r: "Japón" },
{ p: "¿Cuál es el récord mundial actual en 100 metros planos?", r: "9.58 segundos (Usain Bolt)" },
{ p: "¿Qué equipo ha ganado más Ligas de Campeones de Europa?", r: "Real Madrid" },
{ p: "¿Qué deporte se juega en el Super Bowl?", r: "Fútbol americano" },
{ p: "¿Quién fue el primer latinoamericano campeón mundial de Fórmula 1?", r: "Juan Manuel Fangio" },
{ p: "¿Qué país ganó el Mundial de Fútbol en 2006?", r: "Italia" },
{ p: "¿Cuál es el único país que ha participado en todos los Mundiales de fútbol?", r: "Brasil" },
{ p: "¿Qué nadador ha ganado más medallas olímpicas?", r: "Michael Phelps" },
{ p: "¿Cuál es el nombre del trofeo que se entrega en Wimbledon?", r: "La copa dorada (Gentlemen’s Singles Trophy)" },
{ p: "¿En qué deporte se compite en el Tour de Francia?", r: "Ciclismo" },
{ p: "¿Cuántos jugadores hay en un equipo de baloncesto en cancha?", r: "5" },
{ p: "¿En qué país se celebraron los Juegos Olímpicos de 2012?", r: "Reino Unido (Londres)" },
{ p: "¿Qué país ganó la Eurocopa 2021?", r: "Italia" },
{ p: "¿Cuál es el nombre del estadio del FC Barcelona?", r: "Spotify Camp Nou" },
{ p: "¿Qué país tiene más medallas olímpicas en gimnasia artística?", r: "Estados Unidos" },
{ p: "¿Qué exfutbolista es conocido como 'O Rei'?", r: "Pelé" },
{ p: "¿Qué deporte se juega con un bate y una pelota dura en diamante?", r: "Béisbol" },
{ p: "¿Qué equipo de fútbol inglés es apodado 'The Reds'?", r: "Liverpool" },
{ p: "¿Cuántos minutos dura un partido de fútbol profesional?", r: "90 minutos" },
{ p: "¿Qué atleta ganó 4 oros en los JJ.OO. de Berlín 1936?", r: "Jesse Owens" },
{ p: "¿Qué jugador ganó más títulos de Roland Garros?", r: "Rafael Nadal" },
{ p: "¿En qué país nació Diego Maradona?", r: "Argentina" },
{ p: "¿Qué país ganó el Mundial de Rugby 2023?", r: "Sudáfrica" },
{ p: "¿En qué deporte se destacan Novak Djokovic y Rafael Nadal?", r: "Tenis" },
{ p: "¿Qué ciudad fue sede de los JJ.OO. de 1992?", r: "Barcelona" },
{ p: "¿Qué selección ganó el Mundial de 2014?", r: "Alemania" },
{ p: "¿Qué jugadora de tenis ha ganado más Grand Slams femeninos?", r: "Serena Williams" },
{ p: "¿Qué corredor español ganó la Vuelta a España 2008?", r: "Alberto Contador" }
{ p: "¿Qué futbolista fue apodado 'El Fenómeno'?", r: "Ronaldo Nazário" },
{ p: "¿Qué país ganó la Copa Mundial Femenina de Fútbol en 2023?", r: "España" },
{ p: "¿Cuál es el equipo más ganador de la Copa Libertadores?", r: "Independiente (Argentina)" },
{ p: "¿Qué ciudad fue sede de los Juegos Olímpicos de 2008?", r: "Pekín" },
{ p: "¿Qué golfista es conocido como 'El Tigre'?", r: "Tiger Woods" },
{ p: "¿Cuántos puntos vale un triple en baloncesto?", r: "3" },
{ p: "¿Qué futbolista colombiano fue goleador de Italia y Francia?", r: "Radamel Falcao" },
{ p: "¿En qué deporte compite Simone Biles?", r: "Gimnasia artística" },
{ p: "¿Qué país ganó el Mundial de Fútbol Sub-20 en 2023?", r: "Uruguay" },
{ p: "¿Qué selección ganó la Copa Oro 2023?", r: "México" },
{ p: "¿En qué deporte se usa un disco volador?", r: "Ultimate frisbee" },
{ p: "¿Quién fue campeón de la Fórmula 1 en 2023?", r: "Max Verstappen" },
{ p: "¿En qué país nació Zinedine Zidane?", r: "Francia" },
{ p: "¿Cuál es el nombre del estadio del Real Madrid?", r: "Santiago Bernabéu" },
{ p: "¿Cuántos anillos de la NBA tiene LeBron James?", r: "4" },
{ p: "¿Qué deporte combina esquí y tiro?", r: "Biatlón" },
{ p: "¿Qué selección ganó la Copa América en 2019?", r: "Brasil" },
{ p: "¿Qué futbolista es apodado 'El Fideo'?", r: "Ángel Di María" },
{ p: "¿Qué selección ganó el Mundial de Fútbol en 2022?", r: "Argentina" },
{ p: "¿Quién ganó el Balón de Oro en 2022?", r: "Karim Benzema" },
{ p: "¿Cuál es la distancia oficial de un maratón?", r: "42,195 km" },
{ p: "¿Qué jugadora de tenis japonesa ganó el US Open 2018?", r: "Naomi Osaka" },
{ p: "¿Qué país ganó el Mundial de Baloncesto FIBA 2023?", r: "Alemania" },
{ p: "¿Qué equipo ganó la Champions League 2023?", r: "Manchester City" },
{ p: "¿Qué país tiene como deporte nacional el sumo?", r: "Japón" },
{ p: "¿Qué atleta etíope ganó dos oros olímpicos en 10.000 m?", r: "Haile Gebrselassie" },
{ p: "¿Qué colombiano ha sido podio en Tour, Giro y Vuelta?", r: "Rigoberto Urán" },
{ p: "¿Qué arquero alemán ganó el Mundial 2014?", r: "Manuel Neuer" },
{ p: "¿Qué selección ganó la Copa Africana de Naciones en 2022?", r: "Senegal" },
{ p: "¿Qué piloto colombiano ha corrido en la F1 y la IndyCar?", r: "Juan Pablo Montoya" },
{ p: "¿En qué ciudad se juega el torneo de tenis Roland Garros?", r: "París" },
{ p: "¿Qué nadadora estadounidense ganó 7 medallas en Tokio 2020?", r: "Katie Ledecky" },
{ p: "¿Qué selección ha ganado más Eurocopas?", r: "Alemania" },
{ p: "¿Qué boxeador mexicano es conocido como 'Canelo'?", r: "Saúl Álvarez" },
{ p: "¿Qué jugador de la NBA es apodado 'The Greek Freak'?", r: "Giannis Antetokounmpo" },
{ p: "¿Qué ciclista ganó el Tour de Francia 2023?", r: "Jonas Vingegaard" },
{ p: "¿En qué año debutó Messi en el FC Barcelona?", r: "2004" },
{ p: "¿Qué club es apodado 'La Vecchia Signora'?", r: "Juventus" },
{ p: "¿Qué país fue sede de la Copa Mundial de la FIFA 2022?", r: "Catar" },
{ p: "¿Qué equipo es conocido como 'Los Diablos Rojos'?", r: "Manchester United" },
{ p: "¿Qué deportista colombiano ganó oro en levantamiento de pesas en Tokio 2020?", r: "Luis Javier Mosquera" },
{ p: "¿Qué país tiene más títulos en el Mundial Femenino de Fútbol?", r: "Estados Unidos" },
{ p: "¿Qué gimnasta rumana logró el primer 10 perfecto en unas Olimpiadas?", r: "Nadia Comăneci" },
{ p: "¿Qué selección ganó la Copa América Centenario?", r: "Chile" },
{ p: "¿Qué deporte mezcla natación, ciclismo y carrera?", r: "Triatlón" },
{ p: "¿Qué es un 'hat-trick' en fútbol?", r: "Tres goles en un mismo partido" },
{ p: "¿Qué país ha ganado más veces el Mundial de Rugby?", r: "Nueva Zelanda" },
{ p: "¿Qué es el 'clásico del fútbol español'?", r: "Real Madrid vs Barcelona" },
{ p: "¿Qué futbolista portugués ganó 5 Balones de Oro?", r: "Cristiano Ronaldo" }

  ],

  rosa: [
    // Entretenimiento - 200 preguntas
{ p: "¿Quién interpretó a Jack en la película Titanic?", r: "Leonardo DiCaprio" },
{ p: "¿Qué banda británica lanzó el álbum 'Abbey Road'?", r: "The Beatles" },
{ p: "¿Qué película ganó el Oscar a Mejor Película en 2020?", r: "Parásitos" },
{ p: "¿Quién es el creador de la serie animada 'Los Simpson'?", r: "Matt Groening" },
{ p: "¿Cuál es el superhéroe cuyo nombre real es Bruce Wayne?", r: "Batman" },
{ p: "¿Qué cantante es conocida como 'La Reina del Pop'?", r: "Madonna" },
{ p: "¿Qué saga cinematográfica tiene personajes como Frodo y Gandalf?", r: "El Señor de los Anillos" },
{ p: "¿Quién protagonizó la serie de televisión 'Breaking Bad' como Walter White?", r: "Bryan Cranston" },
{ p: "¿Qué película de Disney tiene una princesa llamada Elsa?", r: "Frozen" },
{ p: "¿En qué año se estrenó la primera película de Harry Potter?", r: "2001" },
{ p: "¿Qué actor interpretó a Tony Stark en el Universo Cinematográfico de Marvel?", r: "Robert Downey Jr." },
{ p: "¿Quién cantó 'Thriller'?", r: "Michael Jackson" },
{ p: "¿Qué personaje de Marvel empuña un martillo llamado Mjolnir?", r: "Thor" },
{ p: "¿Quién es el director de cine de 'Titanic', 'Avatar' y 'Terminator'?", r: "James Cameron" },
{ p: "¿Qué serie gira en torno a un trono y casas nobles como Stark y Lannister?", r: "Game of Thrones" },
{ p: "¿Cuál es la plataforma de streaming que lanzó 'Stranger Things'?", r: "Netflix" },
{ p: "¿Qué actor interpretó a Joker en 'The Dark Knight'?", r: "Heath Ledger" },
{ p: "¿Qué cantante es conocida por el álbum '1989'?", r: "Taylor Swift" },
{ p: "¿Qué película animada presenta a un vaquero llamado Woody?", r: "Toy Story" },
{ p: "¿Qué saga de películas se desarrolla en una galaxia muy, muy lejana?", r: "Star Wars" },
{ p: "¿Quién ganó el Latin Grammy a Álbum del Año en 2023?", r: "Shakira" },
{ p: "¿Qué cantante colombiano interpreta 'Felices los 4'?", r: "Maluma" },
{ p: "¿En qué país nació la cantante Rosalía?", r: "España" },
{ p: "¿Cuál es el verdadero nombre de Bad Bunny?", r: "Benito Antonio Martínez Ocasio" },
{ p: "¿Qué serie animada presenta a un niño con una piedra verde mágica llamada Omnitrix?", r: "Ben 10" },
{ p: "¿Qué actor interpreta a Spider-Man en el MCU desde 2016?", r: "Tom Holland" },
{ p: "¿Qué serie cuenta la historia de un ajedrecista llamado Beth Harmon?", r: "Gambito de dama" },
{ p: "¿Qué película cuenta la historia de una muñeca Barbie en el mundo real?", r: "Barbie (2023)" },
{ p: "¿Quién interpreta a Wednesday Addams en la serie de Netflix de 2022?", r: "Jenna Ortega" },
{ p: "¿Qué personaje tiene un amigo llamado Patrick y vive en una piña?", r: "Bob Esponja" },
{ p: "¿Cuál es el apellido de los hermanos protagonistas de 'Supernatural'?", r: "Winchester" },
{ p: "¿Qué banda lanzó la canción 'Bohemian Rhapsody'?", r: "Queen" },
{ p: "¿Qué película es famosa por la frase 'Say hello to my little friend'?", r: "Scarface" },
{ p: "¿Qué actor es conocido por sus papeles en 'El Padrino' y 'Scarface'?", r: "Al Pacino" },
{ p: "¿Qué cantante lanzó el álbum 'Future Nostalgia'?", r: "Dua Lipa" },
{ p: "¿Qué director es conocido por películas como 'Pulp Fiction' y 'Kill Bill'?", r: "Quentin Tarantino" },
{ p: "¿Qué famosa serie coreana ganó popularidad mundial en 2021?", r: "El juego del calamar" },
{ p: "¿Quién interpreta a Deadpool en las películas?", r: "Ryan Reynolds" },
{ p: "¿Qué actor es conocido por interpretar a Wolverine?", r: "Hugh Jackman" },
{ p: "¿Qué comediante protagoniza la película 'Click'?", r: "Adam Sandler" },
{ p: "¿Qué saga de películas tiene a Katniss Everdeen como protagonista?", r: "Los Juegos del Hambre" },
{ p: "¿Qué actriz interpreta a Harley Quinn en el DCEU?", r: "Margot Robbie" },
{ p: "¿En qué serie aparece un grupo llamado 'Los Padrinos Mágicos'?", r: "Los Padrinos Mágicos" },
{ p: "¿Qué película se basa en la vida de Freddie Mercury?", r: "Bohemian Rhapsody" },
{ p: "¿Qué actor interpreta a John Wick?", r: "Keanu Reeves" },
{ p: "¿Qué personaje dice 'Hakuna Matata' en El Rey León?", r: "Timon y Pumba" },
{ p: "¿Qué grupo musical interpreta la canción 'Dynamite'?", r: "BTS" },
{ p: "¿Qué cantante mexicana es conocida por 'Amor Prohibido' y 'Como la Flor'?", r: "Selena Quintanilla" }
{ p: "¿Quién dirigió la película 'Inception'?", r: "Christopher Nolan" },
{ p: "¿Cuál es el nombre real del cantante conocido como Lady Gaga?", r: "Stefani Joanne Angelina Germanotta" },
{ p: "¿En qué serie aparece el personaje Walter White?", r: "Breaking Bad" },
{ p: "¿Qué película protagonizó Keanu Reeves como un agente en Matrix?", r: "Matrix" },
{ p: "¿Quién compuso la música de la saga 'Star Wars'?", r: "John Williams" },
{ p: "¿Cuál es el nombre del mago en 'Harry Potter' que no es Harry?", r: "Albus Dumbledore" },
{ p: "¿Qué cantante lanzó el álbum '25' en 2015?", r: "Adele" },
{ p: "¿Qué actor interpreta a Jack Sparrow en 'Piratas del Caribe'?", r: "Johnny Depp" },
{ p: "¿En qué serie animada aparece un personaje llamado Rick y otro llamado Morty?", r: "Rick y Morty" },
{ p: "¿Qué película animada tiene un personaje llamado Simba?", r: "El Rey León" },
{ p: "¿Quién es el autor de la saga 'Canción de hielo y fuego' en la que se basa 'Game of Thrones'?", r: "George R. R. Martin" },
{ p: "¿Qué cantante es conocido como 'El Rey del Pop'?", r: "Michael Jackson" },
{ p: "¿Cuál es el nombre de la princesa en la película 'La Bella y la Bestia'?", r: "Bella" },
{ p: "¿Qué serie protagonizan los personajes Eleven y Mike?", r: "Stranger Things" },
{ p: "¿Quién es el actor principal de la película 'Forrest Gump'?", r: "Tom Hanks" },
{ p: "¿Qué cantante lanzó la canción 'Shape of You'?", r: "Ed Sheeran" },
{ p: "¿Qué película de Disney tiene personajes llamados Ana y Elsa?", r: "Frozen" },
{ p: "¿Qué actor interpreta a Deadpool en el cine?", r: "Ryan Reynolds" },
{ p: "¿En qué año se estrenó la primera película de 'Toy Story'?", r: "1995" },
{ p: "¿Qué cantante es famoso por la canción 'Bad Guy'?", r: "Billie Eilish" },
{ p: "¿Cuál es el nombre del personaje principal en la serie 'Sherlock'?", r: "Sherlock Holmes" },
{ p: "¿Qué actor interpretó a Capitán América en las películas de Marvel?", r: "Chris Evans" },
{ p: "¿Qué película de terror protagoniza el payaso Pennywise?", r: "It (Eso)" },
{ p: "¿Quién dirigió la trilogía de 'El Hobbit'?", r: "Peter Jackson" },
{ p: "¿Qué cantante es conocido por sus canciones como 'Hello' y 'Rolling in the Deep'?", r: "Adele" },
{ p: "¿Cuál es la serie animada en la que aparece Bob Esponja?", r: "Bob Esponja" },
{ p: "¿Qué actor protagonizó la saga de películas 'John Wick'?", r: "Keanu Reeves" },
{ p: "¿En qué serie aparece el personaje Daenerys Targaryen?", r: "Game of Thrones" },
{ p: "¿Quién ganó el Oscar a Mejor Actor por la película 'Joker' en 2020?", r: "Joaquin Phoenix" },
{ p: "¿Qué película animada presenta a una princesa llamada Rapunzel?", r: "Enredados" },
{ p: "¿Qué grupo musical lanzó el álbum 'Thriller'?", r: "Michael Jackson" },
{ p: "¿Qué actriz protagonizó la película 'La La Land'?", r: "Emma Stone" },
{ p: "¿Quién es el creador de la serie 'Stranger Things'?", r: "Los hermanos Duffer" },
{ p: "¿Qué actor interpretó a Wolverine?", r: "Hugh Jackman" },
{ p: "¿Qué película protagoniza Tom Cruise como Ethan Hunt?", r: "Misión Imposible" },
{ p: "¿Qué cantante es conocido como 'La Voz' en Colombia?", r: "Shakira" },
{ p: "¿Cuál es el nombre del robot en la película 'Wall-E'?", r: "Wall-E" },
{ p: "¿Qué cantante lanzó la canción 'Rolling in the Deep'?", r: "Adele" },
{ p: "¿En qué película aparece el personaje llamado Buzz Lightyear?", r: "Toy Story" },
{ p: "¿Qué actor protagoniza la serie 'The Mandalorian'?", r: "Pedro Pascal" },
{ p: "¿Cuál es el nombre del villano en 'Los Increíbles'?", r: "Síndrome" },
{ p: "¿Qué actriz protagonizó la película 'Mujer Maravilla'?", r: "Gal Gadot" },
{ p: "¿Qué serie animada tiene a una familia llamada los Griffin?", r: "Padre de familia" },
{ p: "¿Quién dirigió la película 'Pulp Fiction'?", r: "Quentin Tarantino" },
{ p: "¿Qué película protagonizó Leonardo DiCaprio y está ambientada en la época de la Gran Depresión?", r: "El aviador" },
{ p: "¿Qué cantante lanzó el álbum 'Lover' en 2019?", r: "Taylor Swift" },
{ p: "¿Quién es la protagonista de la serie 'Killing Eve'?", r: "Sandra Oh" }


  ],
};

let indices = {
  cafe: 0,
  verde: 0,
  beige: 0,
  azul: 0,
  rosa: 0
};

let preguntaActual = null;

function mostrarPregunta(categoria) {
  if (!preguntas[categoria]) {
    document.getElementById("pregunta").innerHTML = "Categoría no encontrada.";
    document.getElementById("respuesta").innerHTML = "";
    return;
  }

  const lista = preguntas[categoria];
  let i = indices[categoria];

  if (i < lista.length) {
    preguntaActual = lista[i];
    document.getElementById("pregunta").innerHTML = `<strong>${preguntaActual.p}</strong>`;
    document.getElementById("respuesta").innerHTML = "";
    indices[categoria]++;
  } else {
    document.getElementById("pregunta").innerHTML = "Ya no hay más preguntas en esta categoría.";
    document.getElementById("respuesta").innerHTML = "";
  }
}

function mostrarRespuesta() {
  if (preguntaActual) {
    document.getElementById("respuesta").innerHTML = preguntaActual.r;
  } else {
    document.getElementById("respuesta").innerHTML = "Primero elige una categoría.";
  }
}
