const preguntas = {
  cafe: [
    // Historia - 200 preguntas
  { p: "¿Quién fue el primer presidente de Estados Unidos?", r: "George Washington" },
  { p: "¿En qué año comenzó la Segunda Guerra Mundial?", r: "1939" },
  { p: "¿Qué civilización construyó las pirámides?", r: "Los egipcios" },
  { p: "¿Quién descubrió América?", r: "Cristóbal Colón" },
  { p: "¿En qué año cayó el Muro de Berlín?", r: "1989" },
  { p: "¿Qué imperio dominó gran parte de Sudamérica antes de la llegada de los españoles?", r: "El Imperio Inca" },
  { p: "¿Cuál fue la causa principal de la Revolución Francesa?", r: "La desigualdad social y económica" },
  { p: "¿Quién fue Napoleón Bonaparte?", r: "Un líder militar y emperador francés" },
  { p: "¿Cuál fue el resultado de la Guerra Civil de Estados Unidos?", r: "La abolición de la esclavitud" },
  { p: "¿Qué tratado puso fin a la Primera Guerra Mundial?", r: "El Tratado de Versalles" },
  { p: "¿Quién fue la Reina de Inglaterra durante la época isabelina?", r: "Isabel I" },
  { p: "¿Qué civilización antigua se ubicaba en Mesopotamia?", r: "Los sumerios" },
  { p: "¿Qué evento marcó el inicio de la Edad Media?", r: "La caída del Imperio Romano de Occidente" },
  { p: "¿Quién fue Simón Bolívar?", r: "Un líder de la independencia de varios países sudamericanos" },
  { p: "¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", r: "1776" },
  { p: "¿Qué fue la Guerra Fría?", r: "Un conflicto ideológico entre EE.UU. y la URSS" },
  { p: "¿Qué evento detonó la Primera Guerra Mundial?", r: "El asesinato del archiduque Francisco Fernando" },
  { p: "¿Quién fue Mahatma Gandhi?", r: "Líder del movimiento de independencia de India" },
  { p: "¿Qué imperio dominó gran parte de Europa durante la Edad Media?", r: "El Imperio Romano Germánico" },
  { p: "¿Qué civilización construyó Machu Picchu?", r: "Los incas" },
  { p: "¿Qué era la ruta de la seda?", r: "Una red de rutas comerciales entre Asia y Europa" },
  { p: "¿Cuál fue la capital del Imperio Azteca?", r: "Tenochtitlán" },
  { p: "¿Qué país fue conocido como la URSS?", r: "La Unión Soviética" },
  { p: "¿En qué año terminó la Primera Guerra Mundial?", r: "1918" },
{ p: "¿Qué guerra se libró entre el norte y el sur de EE.UU.?", r: "La Guerra Civil" },
{ p: "¿Quién fue el dictador italiano durante la Segunda Guerra Mundial?", r: "Benito Mussolini" },
{ p: "¿Qué imperio construyó el Coliseo?", r: "El Imperio Romano" },
{ p: "¿Quién fue el primer emperador romano?", r: "Augusto" },
{ p: "¿Qué civilización usaba jeroglíficos?", r: "La egipcia" },
{ p: "¿Qué líder sudafricano luchó contra el apartheid?", r: "Nelson Mandela" },
{ p: "¿Qué país lanzó las bombas atómicas en Hiroshima y Nagasaki?", r: "Estados Unidos" },
{ p: "¿Qué tratado puso fin a la Primera Guerra Mundial?", r: "El Tratado de Versalles" },
{ p: "¿Quién fue el zar durante la Revolución Rusa?", r: "Nicolás II" },
{ p: "¿Qué país fue invadido por Alemania para iniciar la Segunda Guerra Mundial?", r: "Polonia" },
{ p: "¿En qué año comenzó la Revolución Francesa?", r: "1789" },
{ p: "¿Qué imperio estaba gobernado por los zares?", r: "El Imperio Ruso" },
{ p: "¿Qué evento ocurrió el 11 de septiembre de 2001?", r: "Los atentados a las Torres Gemelas" },
{ p: "¿Cuál fue la última dinastía china?", r: "La dinastía Qing" },
{ p: "¿Quién era el líder de los nazis?", r: "Adolf Hitler" },
{ p: "¿Qué guerra enfrentó a EE.UU. con Vietnam?", r: "La Guerra de Vietnam" },
{ p: "¿Quién descubrió la ruta marítima a la India?", r: "Vasco da Gama" },
{ p: "¿Quién fue Juana de Arco?", r: "Una heroína francesa y santa" },
{ p: "¿Qué país colonizó gran parte de América del Sur?", r: "España" },
{ p: "¿Quién fue Simón Bolívar?", r: "El Libertador de América del Sur" },
{ p: "¿Qué civilización creó el calendario maya?", r: "La civilización maya" },
{ p: "¿Quién escribió la Constitución de EE.UU.?", r: "Varios padres fundadores" },
{ p: "¿Qué imperio cayó en 1453?", r: "El Imperio Bizantino" },
{ p: "¿Qué rey francés fue guillotinado durante la Revolución?", r: "Luis XVI" },
{ p: "¿Qué conflicto se llamó la Gran Guerra?", r: "La Primera Guerra Mundial" },
{ p: "¿Qué país fue gobernado por Stalin?", r: "La Unión Soviética" },

  ],

  verde: [
    // Ciencia - 200 preguntas
{ p: "¿Cuál es el órgano encargado de bombear sangre en el cuerpo humano?", r: "El corazón" },
{ p: "¿Qué planeta es conocido como el planeta rojo?", r: "Marte" },
{ p: "¿Qué gas es esencial para la respiración humana?", r: "Oxígeno" },
{ p: "¿Qué científico formuló la teoría de la relatividad?", r: "Albert Einstein" },
{ p: "¿Cómo se llama el proceso por el cual las plantas fabrican su alimento?", r: "Fotosíntesis" },
{ p: "¿Cuál es el hueso más largo del cuerpo humano?", r: "El fémur" },
{ p: "¿Qué partícula tiene carga negativa?", r: "Electrón" },
{ p: "¿Qué tipo de energía proviene del sol?", r: "Energía solar" },
{ p: "¿Qué mamífero pone huevos?", r: "Ornitorrinco" },
{ p: "¿Qué órgano es responsable de filtrar la sangre?", r: "Riñón" },
{ p: "¿Qué planeta tiene un sistema de anillos?", r: "Saturno" },
{ p: "¿Cómo se llama la fuerza que nos mantiene en el suelo?", r: "Gravedad" },
{ p: "¿Qué metal se encuentra en el centro de la Tierra?", r: "Hierro" },
{ p: "¿Qué parte del ojo regula la entrada de luz?", r: "La pupila" },
{ p: "¿Qué instrumento se usa para medir la temperatura?", r: "Termómetro" },
{ p: "¿Qué animales son conocidos por su metamorfosis completa?", r: "Las mariposas" },
{ p: "¿Qué enfermedad afectó al mundo en 2020?", r: "COVID-19" },
{ p: "¿Qué órgano produce insulina?", r: "El páncreas" },
{ p: "¿Cuál es el planeta más cercano al Sol?", r: "Mercurio" },
{ p: "¿Qué sistema corporal controla los movimientos voluntarios?", r: "Sistema nervioso" },
{ p: "¿Qué gas es el más abundante en la atmósfera?", r: "Nitrógeno" },
{ p: "¿Qué parte de la planta absorbe nutrientes del suelo?", r: "Las raíces" },
{ p: "¿Qué animales pertenecen al grupo de los anfibios?", r: "Ranas, sapos y salamandras" },
{ p: "¿Qué órgano permite respirar a los humanos?", r: "Pulmones" },
{ p: "¿Qué tipo de célula no tiene núcleo definido?", r: "Procariota" },
{ p: "¿Qué tipo de sangre es el donante universal?", r: "O negativo" },
{ p: "¿Qué astro da luz y calor a la Tierra?", r: "El Sol" },
{ p: "¿Cómo se llama la ciencia que estudia los seres vivos?", r: "Biología" },
{ p: "¿Qué vitamina se obtiene del sol?", r: "Vitamina D" },
{ p: "¿Qué animal puede regenerar sus extremidades?", r: "La estrella de mar" },
{ p: "¿Qué fenómeno meteorológico produce rayos y truenos?", r: "Tormenta eléctrica" },
{ p: "¿Qué planeta es el más grande del sistema solar?", r: "Júpiter" },
{ p: "¿Qué unidad se usa para medir la intensidad eléctrica?", r: "Amperio" },
{ p: "¿Qué nombre recibe el ADN en las células?", r: "Material genético" },
{ p: "¿Qué órgano conecta la boca con el estómago?", r: "Esófago" },
{ p: "¿Cómo se llama el estudio de los fósiles?", r: "Paleontología" },
{ p: "¿Qué parte del cuerpo produce glóbulos rojos?", r: "Médula ósea" },
{ p: "¿Qué órgano es responsable de la digestión química?", r: "El estómago" },
{ p: "¿Qué nombre recibe el agua en estado gaseoso?", r: "Vapor" },
{ p: "¿Qué fenómeno hace que los objetos floten en el agua?", r: "Empuje o flotación" },
{ p: "¿Cuál es el único satélite natural de la Tierra?", r: "La Luna" },
{ p: "¿Qué aparato se usa para ver objetos muy pequeños?", r: "Microscopio" },
{ p: "¿Qué animal es el más rápido del mundo?", r: "El halcón peregrino" },
{ p: "¿Qué proceso permite que el hielo se convierta en agua?", r: "Fusión" },
{ p: "¿Qué líquido del cuerpo transporta oxígeno?", r: "La sangre" },
{ p: "¿Qué es un eclipse?", r: "La ocultación de un cuerpo celeste por otro" },
{ p: "¿Qué parte del cerebro controla el equilibrio?", r: "El cerebelo" },
{ p: "¿Qué planeta tiene un día más largo que su año?", r: "Venus" },
{ p: "¿Qué ciencia estudia los planetas y estrellas?", r: "Astronomía" },
{ p: "¿Qué órgano produce bilis?", r: "El hígado" }
  ],

  beige: [
    // Arte y Literatura - 200 preguntas
{ p: "¿Quién escribió *Cien años de soledad*?", r: "Gabriel García Márquez" },
{ p: "¿Qué pintor es conocido por cortarse una oreja?", r: "Vincent van Gogh" },
{ p: "¿Quién escribió *Don Quijote de la Mancha*?", r: "Miguel de Cervantes" },
{ p: "¿Qué escritor británico creó al personaje de Harry Potter?", r: "J.K. Rowling" },
{ p: "¿En qué país nació Pablo Picasso?", r: "España" },
{ p: "¿Cuál es la obra más famosa de Leonardo da Vinci?", r: "La Mona Lisa" },
{ p: "¿Qué autor escribió *Romeo y Julieta*?", r: "William Shakespeare" },
{ p: "¿Qué poeta chileno ganó el Nobel en 1971?", r: "Pablo Neruda" },
{ p: "¿Quién pintó el techo de la Capilla Sixtina?", r: "Miguel Ángel" },
{ p: "¿Cuál es el verdadero nombre de Mark Twain?", r: "Samuel Langhorne Clemens" },
{ p: "¿Qué novela comienza con 'En un lugar de la Mancha'?", r: "*Don Quijote de la Mancha*" },
{ p: "¿Qué es un haiku?", r: "Un poema japonés corto" },
{ p: "¿Quién escribió *La Divina Comedia*?", r: "Dante Alighieri" },
{ p: "¿Qué movimiento artístico fundó Salvador Dalí?", r: "Surrealismo" },
{ p: "¿Qué autor escribió *Crimen y castigo*?", r: "Fiódor Dostoyevski" },
{ p: "¿Qué pintor español es famoso por sus obras cubistas?", r: "Pablo Picasso" },
{ p: "¿Quién escribió *El principito*?", r: "Antoine de Saint-Exupéry" },
{ p: "¿Qué escritor argentino es autor de *Ficciones*?", r: "Jorge Luis Borges" },
{ p: "¿Qué autor escribió *1984* y *Rebelión en la granja*?", r: "George Orwell" },
{ p: "¿Qué artista pintó *La noche estrellada*?", r: "Vincent van Gogh" },
{ p: "¿Quién escribió *Rayuela*?", r: "Julio Cortázar" },
{ p: "¿Qué obra escribió Homero además de *La Ilíada*?", r: "*La Odisea*" },
{ p: "¿Qué escritor noruego escribió *Casa de muñecas*?", r: "Henrik Ibsen" },
{ p: "¿Qué es un soneto?", r: "Un poema de 14 versos" },
{ p: "¿Quién escribió *El amor en los tiempos del cólera*?", r: "Gabriel García Márquez" },
{ p: "¿Quién es el autor de *Pedro Páramo*?", r: "Juan Rulfo" },
{ p: "¿Qué famoso pintor usó el método del puntillismo?", r: "Georges Seurat" },
{ p: "¿Qué dramaturgo español escribió *La vida es sueño*?", r: "Calderón de la Barca" },
{ p: "¿Qué poeta escribió *Alturas de Macchu Picchu*?", r: "Pablo Neruda" },
{ p: "¿Qué escritora mexicana ganó el Premio Cervantes en 2013?", r: "Elena Poniatowska" },
{ p: "¿Qué novela de Mary Shelley es considerada la primera de ciencia ficción?", r: "*Frankenstein*" },
{ p: "¿Qué escultor renacentista creó *El David*?", r: "Miguel Ángel" },
{ p: "¿Qué poeta escribió *Campos de Castilla*?", r: "Antonio Machado" },
{ p: "¿Quién pintó *El Guernica*?", r: "Pablo Picasso" },
{ p: "¿Qué obra literaria trata del capitán Ahab y una ballena?", r: "*Moby Dick*" },
{ p: "¿Qué autor escribió *La Metamorfosis*?", r: "Franz Kafka" },
{ p: "¿Qué escritor ruso es autor de *Ana Karenina*?", r: "León Tolstói" },
{ p: "¿Qué corriente artística prioriza la expresión emocional?", r: "Expresionismo" },
{ p: "¿Qué pintor español es famoso por sus pinturas negras?", r: "Francisco de Goya" },
{ p: "¿Quién escribió *Los miserables*?", r: "Victor Hugo" },
{ p: "¿Qué poeta escribió *Rimas y leyendas*?", r: "Gustavo Adolfo Bécquer" },
{ p: "¿Qué escritor escribió *El túnel*?", r: "Ernesto Sabato" },
{ p: "¿Qué autor creó a Sherlock Holmes?", r: "Arthur Conan Doyle" },
{ p: "¿Qué poeta escribió *Oda a la alegría*?", r: "Friedrich Schiller" },
{ p: "¿Qué autora escribió *Orgullo y prejuicio*?", r: "Jane Austen" },
{ p: "¿Qué corriente artística pintó Monet?", r: "Impresionismo" },
{ p: "¿Qué autor escribió *Fahrenheit 451*?", r: "Ray Bradbury" },
{ p: "¿Qué escritor colombiano escribió *El coronel no tiene quien le escriba*?", r: "Gabriel García Márquez" },
{ p: "¿Qué libro tiene como personaje principal a Gregorio Samsa?", r: "*La Metamorfosis*" },
{ p: "¿Qué pintor mexicano es conocido por su estilo muralista?", r: "Diego Rivera" }

  ],

  azul: [
    // Deportes - 200 preguntas
{ p: "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?", r: "1896" },
{ p: "¿Cuál es el país con más Copas del Mundo de fútbol ganadas?", r: "Brasil" },
{ p: "¿Qué tenista ha ganado más títulos de Grand Slam?", r: "Novak Djokovic" },
{ p: "¿Qué futbolista es conocido como 'La Pulga'?", r: "Lionel Messi" },
{ p: "¿En qué deporte se usa una tabla y una vela?", r: "Windsurf" },
{ p: "¿Qué selección ganó el Mundial de Fútbol en 2018?", r: "Francia" },
{ p: "¿Qué país ha ganado más medallas olímpicas en total?", r: "Estados Unidos" },
{ p: "¿Cuál es el deporte principal en India?", r: "Críquet" },
{ p: "¿Quién es el máximo goleador histórico de la Champions League?", r: "Cristiano Ronaldo" },
{ p: "¿En qué país se celebraron los Juegos Olímpicos de 2020?", r: "Japón" },
{ p: "¿Cuántos jugadores hay en un equipo de voleibol en cancha?", r: "6" },
{ p: "¿Qué ciclista ganó 7 Tours de Francia consecutivos?", r: "Lance Armstrong (títulos luego retirados)" },
{ p: "¿Cuál es el equipo con más títulos en la NBA?", r: "Boston Celtics" },
{ p: "¿Qué deportista es apodado 'Bolt'?", r: "Usain Bolt" },
{ p: "¿Qué boxeador fue conocido como 'The Greatest'?", r: "Muhammad Ali" },
{ p: "¿En qué deporte se destacan los All Blacks?", r: "Rugby" },
{ p: "¿Cuántos sets se juegan en un partido de tenis masculino de Grand Slam?", r: "5" },
{ p: "¿Cuál es el país con más títulos en la Copa Davis?", r: "Estados Unidos" },
{ p: "¿Qué piloto de Fórmula 1 tiene más campeonatos mundiales?", r: "Lewis Hamilton (empatado con Schumacher)" },
{ p: "¿Quién fue el primer campeón mundial de ajedrez?", r: "Wilhelm Steinitz" },
{ p: "¿Qué futbolista argentino ganó el Balón de Oro en 2023?", r: "Lionel Messi" },
{ p: "¿En qué país se originó el judo?", r: "Japón" },
{ p: "¿Cuál es el récord mundial actual en 100 metros planos?", r: "9.58 segundos (Usain Bolt)" },
{ p: "¿Qué equipo ha ganado más Ligas de Campeones de Europa?", r: "Real Madrid" },
{ p: "¿Qué deporte se juega en el Super Bowl?", r: "Fútbol americano" },
{ p: "¿Quién fue el primer latinoamericano campeón mundial de Fórmula 1?", r: "Juan Manuel Fangio" },
{ p: "¿Qué país ganó el Mundial de Fútbol en 2006?", r: "Italia" },
{ p: "¿Cuál es el único país que ha participado en todos los Mundiales de fútbol?", r: "Brasil" },
{ p: "¿Qué nadador ha ganado más medallas olímpicas?", r: "Michael Phelps" },
{ p: "¿Cuál es el nombre del trofeo que se entrega en Wimbledon?", r: "La copa dorada (Gentlemen’s Singles Trophy)" },
{ p: "¿En qué deporte se compite en el Tour de Francia?", r: "Ciclismo" },
{ p: "¿Cuántos jugadores hay en un equipo de baloncesto en cancha?", r: "5" },
{ p: "¿En qué país se celebraron los Juegos Olímpicos de 2012?", r: "Reino Unido (Londres)" },
{ p: "¿Qué país ganó la Eurocopa 2021?", r: "Italia" },
{ p: "¿Cuál es el nombre del estadio del FC Barcelona?", r: "Spotify Camp Nou" },
{ p: "¿Qué país tiene más medallas olímpicas en gimnasia artística?", r: "Estados Unidos" },
{ p: "¿Qué exfutbolista es conocido como 'O Rei'?", r: "Pelé" },
{ p: "¿Qué deporte se juega con un bate y una pelota dura en diamante?", r: "Béisbol" },
{ p: "¿Qué equipo de fútbol inglés es apodado 'The Reds'?", r: "Liverpool" },
{ p: "¿Cuántos minutos dura un partido de fútbol profesional?", r: "90 minutos" },
{ p: "¿Qué atleta ganó 4 oros en los JJ.OO. de Berlín 1936?", r: "Jesse Owens" },
{ p: "¿Qué jugador ganó más títulos de Roland Garros?", r: "Rafael Nadal" },
{ p: "¿En qué país nació Diego Maradona?", r: "Argentina" },
{ p: "¿Qué país ganó el Mundial de Rugby 2023?", r: "Sudáfrica" },
{ p: "¿En qué deporte se destacan Novak Djokovic y Rafael Nadal?", r: "Tenis" },
{ p: "¿Qué ciudad fue sede de los JJ.OO. de 1992?", r: "Barcelona" },
{ p: "¿Qué selección ganó el Mundial de 2014?", r: "Alemania" },
{ p: "¿Qué jugadora de tenis ha ganado más Grand Slams femeninos?", r: "Serena Williams" },
{ p: "¿Qué corredor español ganó la Vuelta a España 2008?", r: "Alberto Contador" }

  ],

  rosa: [
    // Entretenimiento - 200 preguntas
{ p: "¿Quién interpretó a Jack en la película Titanic?", r: "Leonardo DiCaprio" },
{ p: "¿Qué banda británica lanzó el álbum 'Abbey Road'?", r: "The Beatles" },
{ p: "¿Qué película ganó el Oscar a Mejor Película en 2020?", r: "Parásitos" },
{ p: "¿Quién es el creador de la serie animada 'Los Simpson'?", r: "Matt Groening" },
{ p: "¿Cuál es el superhéroe cuyo nombre real es Bruce Wayne?", r: "Batman" },
{ p: "¿Qué cantante es conocida como 'La Reina del Pop'?", r: "Madonna" },
{ p: "¿Qué saga cinematográfica tiene personajes como Frodo y Gandalf?", r: "El Señor de los Anillos" },
{ p: "¿Quién protagonizó la serie de televisión 'Breaking Bad' como Walter White?", r: "Bryan Cranston" },
{ p: "¿Qué película de Disney tiene una princesa llamada Elsa?", r: "Frozen" },
{ p: "¿En qué año se estrenó la primera película de Harry Potter?", r: "2001" },
{ p: "¿Qué actor interpretó a Tony Stark en el Universo Cinematográfico de Marvel?", r: "Robert Downey Jr." },
{ p: "¿Quién cantó 'Thriller'?", r: "Michael Jackson" },
{ p: "¿Qué personaje de Marvel empuña un martillo llamado Mjolnir?", r: "Thor" },
{ p: "¿Quién es el director de cine de 'Titanic', 'Avatar' y 'Terminator'?", r: "James Cameron" },
{ p: "¿Qué serie gira en torno a un trono y casas nobles como Stark y Lannister?", r: "Game of Thrones" },
{ p: "¿Cuál es la plataforma de streaming que lanzó 'Stranger Things'?", r: "Netflix" },
{ p: "¿Qué actor interpretó a Joker en 'The Dark Knight'?", r: "Heath Ledger" },
{ p: "¿Qué cantante es conocida por el álbum '1989'?", r: "Taylor Swift" },
{ p: "¿Qué película animada presenta a un vaquero llamado Woody?", r: "Toy Story" },
{ p: "¿Qué saga de películas se desarrolla en una galaxia muy, muy lejana?", r: "Star Wars" },
{ p: "¿Quién ganó el Latin Grammy a Álbum del Año en 2023?", r: "Shakira" },
{ p: "¿Qué cantante colombiano interpreta 'Felices los 4'?", r: "Maluma" },
{ p: "¿En qué país nació la cantante Rosalía?", r: "España" },
{ p: "¿Cuál es el verdadero nombre de Bad Bunny?", r: "Benito Antonio Martínez Ocasio" },
{ p: "¿Qué serie animada presenta a un niño con una piedra verde mágica llamada Omnitrix?", r: "Ben 10" },
{ p: "¿Qué actor interpreta a Spider-Man en el MCU desde 2016?", r: "Tom Holland" },
{ p: "¿Qué serie cuenta la historia de un ajedrecista llamado Beth Harmon?", r: "Gambito de dama" },
{ p: "¿Qué película cuenta la historia de una muñeca Barbie en el mundo real?", r: "Barbie (2023)" },
{ p: "¿Quién interpreta a Wednesday Addams en la serie de Netflix de 2022?", r: "Jenna Ortega" },
{ p: "¿Qué personaje tiene un amigo llamado Patrick y vive en una piña?", r: "Bob Esponja" },
{ p: "¿Cuál es el apellido de los hermanos protagonistas de 'Supernatural'?", r: "Winchester" },
{ p: "¿Qué banda lanzó la canción 'Bohemian Rhapsody'?", r: "Queen" },
{ p: "¿Qué película es famosa por la frase 'Say hello to my little friend'?", r: "Scarface" },
{ p: "¿Qué actor es conocido por sus papeles en 'El Padrino' y 'Scarface'?", r: "Al Pacino" },
{ p: "¿Qué cantante lanzó el álbum 'Future Nostalgia'?", r: "Dua Lipa" },
{ p: "¿Qué director es conocido por películas como 'Pulp Fiction' y 'Kill Bill'?", r: "Quentin Tarantino" },
{ p: "¿Qué famosa serie coreana ganó popularidad mundial en 2021?", r: "El juego del calamar" },
{ p: "¿Quién interpreta a Deadpool en las películas?", r: "Ryan Reynolds" },
{ p: "¿Qué actor es conocido por interpretar a Wolverine?", r: "Hugh Jackman" },
{ p: "¿Qué comediante protagoniza la película 'Click'?", r: "Adam Sandler" },
{ p: "¿Qué saga de películas tiene a Katniss Everdeen como protagonista?", r: "Los Juegos del Hambre" },
{ p: "¿Qué actriz interpreta a Harley Quinn en el DCEU?", r: "Margot Robbie" },
{ p: "¿En qué serie aparece un grupo llamado 'Los Padrinos Mágicos'?", r: "Los Padrinos Mágicos" },
{ p: "¿Qué película se basa en la vida de Freddie Mercury?", r: "Bohemian Rhapsody" },
{ p: "¿Qué actor interpreta a John Wick?", r: "Keanu Reeves" },
{ p: "¿Qué personaje dice 'Hakuna Matata' en El Rey León?", r: "Timon y Pumba" },
{ p: "¿Qué grupo musical interpreta la canción 'Dynamite'?", r: "BTS" },
{ p: "¿Qué cantante mexicana es conocida por 'Amor Prohibido' y 'Como la Flor'?", r: "Selena Quintanilla" }

  ],
};

let indices = {
  cafe: 0,
  verde: 0,
  beige: 0,
  azul: 0,
  rosa: 0
};

let preguntaActual = null;

function mostrarPregunta(categoria) {
  if (!preguntas[categoria]) {
    document.getElementById("pregunta").innerHTML = "Categoría no encontrada.";
    document.getElementById("respuesta").innerHTML = "";
    return;
  }

  const lista = preguntas[categoria];
  let i = indices[categoria];

  if (i < lista.length) {
    preguntaActual = lista[i];
    document.getElementById("pregunta").innerHTML = `<strong>${preguntaActual.p}</strong>`;
    document.getElementById("respuesta").innerHTML = "";
    indices[categoria]++;
  } else {
    document.getElementById("pregunta").innerHTML = "Ya no hay más preguntas en esta categoría.";
    document.getElementById("respuesta").innerHTML = "";
  }
}

function mostrarRespuesta() {
  if (preguntaActual) {
    document.getElementById("respuesta").innerHTML = preguntaActual.r;
  } else {
    document.getElementById("respuesta").innerHTML = "Primero elige una categoría.";
  }
}
